# Generated by Django 4.2 on 2025-05-01 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('auditores_acompanantes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Auditores acompañantes')),
                ('lineas_auditadas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lineas de producción auditadas')),
                ('resultado_pdf', models.FileField(blank=True, null=True, upload_to='auditorias/')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.auditor')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usa_puntaje', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ppr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('requisito', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaPredefinida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('texto_critico', models.BooleanField(default=False)),
                ('numero_pregunta', models.CharField(blank=True, max_length=5, null=True)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.checklist')),
            ],
            options={
                'ordering': ['numero_pregunta'],
            },
        ),
        migrations.CreateModel(
            name='TipoNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_respuesta', models.CharField(choices=[('correcto', 'Correcto'), ('parcialmente_correcto', 'Parcialmente Correcto'), ('no_correcto', 'No Correcto'), ('critica', 'Critica')], max_length=21)),
                ('puntaje', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.auditoria')),
                ('pregunta_predefinida', models.ForeignKey(default='correcto', on_delete=django.db.models.deletion.CASCADE, to='questions.preguntapredefinida')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('prr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='questions.ppr')),
            ],
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_norma', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=100)),
                ('norma_pdf', models.FileField(blank=True, null=True, upload_to='normativas/')),
                ('activa', models.BooleanField(default=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.tiposeccion')),
                ('tipo_norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.tiponorma')),
            ],
            options={
                'ordering': ['seccion'],
            },
        ),
        migrations.AddField(
            model_name='auditoria',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.checklist'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.cliente'),
        ),
    ]
