# Generated by Django 4.2 on 2025-04-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('auditores_acompanantes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Auditores acompañantes')),
                ('lineas_auditadas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lineas de producción auditadas')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.auditor')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaPredefinida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('texto_critico', models.BooleanField(default=False)),
                ('numero_pregunta', models.IntegerField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='questions.checklist')),
            ],
            options={
                'ordering': ['numero_pregunta'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_respuesta', models.CharField(choices=[('correcto', 'Correcto'), ('parcialmente_correcto', 'Parcialmente Correcto'), ('no_correcto', 'No Correcto'), ('critica', 'Critica')], max_length=21)),
                ('puntaje', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.auditoria')),
                ('pregunta_predefinida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.preguntapredefinida')),
            ],
        ),
        migrations.AddField(
            model_name='auditoria',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.cliente'),
        ),
    ]
