# Generated by Django 4.2 on 2025-03-26 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.auditor')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaPredefinida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_respuesta', models.CharField(choices=[('correcto', 'Correcto'), ('parcialmente_correcto', 'Parcialmente Correcto'), ('no_correcto', 'No Correcto')], max_length=21)),
                ('puntaje', models.IntegerField()),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.auditoria')),
                ('pregunta_predefinida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.preguntapredefinida')),
            ],
        ),
        migrations.AddField(
            model_name='auditoria',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.cliente'),
        ),
    ]
