# Generated by Django 4.2 on 2025-04-10 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='checklist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.checklist'),
            preserve_default=False,
        ),
    ]
