# Generated by Django 4.2 on 2025-05-05 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haccp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(max_length=30)),
                ('principio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_haccp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('prr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_haccp', to='questions.haccp')),
            ],
        ),
    ]
