# Generated by Django 4.2 on 2025-03-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
