# Generated by Django 4.2 on 2025-04-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_delete_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntapredefinida',
            name='texto_critico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='tipo_respuesta',
            field=models.CharField(choices=[('correcto', 'Correcto'), ('parcialmente_correcto', 'Parcialmente Correcto'), ('no_correcto', 'No Correcto'), ('critica', 'Critica')], max_length=21),
        ),
    ]
