# Generated by Django 4.2 on 2025-04-15 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auditoria_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntapredefinida',
            name='usa_puntaje',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.checklist'),
        ),
        migrations.AlterField(
            model_name='preguntapredefinida',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.checklist'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta_predefinida',
            field=models.ForeignKey(default='correcto', on_delete=django.db.models.deletion.CASCADE, to='questions.preguntapredefinida'),
        ),
    ]
