# Generated by Django 4.2 on 2025-04-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_preguntapredefinida_texto_critico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preguntapredefinida',
            name='texto',
            field=models.TextField(),
        ),
    ]
