# Generated by Django 4.2 on 2025-05-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_prr_ref_haccp_haccp_list_haccp_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haccp',
            name='numero',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='haccp',
            name='principio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
