# Generated by Django 4.2 on 2025-04-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_preguntapredefinida_usa_puntaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
