# Generated by Django 4.2 on 2025-04-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auditoria_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='respuesta_texto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
