# Generated by Django 4.2 on 2025-04-05 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_respuesta_texto_critico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='texto_critico',
        ),
    ]
