# Generated by Django 4.2 on 2025-05-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_noconformidades_ref_noconformidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noconformidades',
            name='nc',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='noconformidades',
            name='seccion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
