# Generated by Django 4.2 on 2025-04-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_respuesta_respuesta_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntapredefinida',
            name='puntaje_maximo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
