# Generated by Django 4.2 on 2025-04-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_preguntapredefinida_puntaje_maximo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='preguntapredefinida',
            name='puntaje_maximo',
        ),
        migrations.RemoveField(
            model_name='preguntapredefinida',
            name='usa_puntaje',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='respuesta_texto',
        ),
        migrations.AddField(
            model_name='preguntapredefinida',
            name='es_evaluacion',
            field=models.BooleanField(default=False),
        ),
    ]
