# Generated by Django 4.2 on 2025-04-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_respuesta_texto_critico'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='auditores_acompanantes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
