# Generated by Django 4.2 on 2025-06-24 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_noconformidades_nc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuestraAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_muestreo', models.DateField()),
                ('lugar_muestreo', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('acta_numero', models.CharField(max_length=10)),
                ('laboratorio', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantaIndustrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('localidadd', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoAnalisisAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoAnalisisAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('A', 'Aceptable'), ('NA', 'No Aceptable')], max_length=2)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('protocolo_pdf', models.FileField(blank=True, null=True, upload_to='analisis_agua/')),
                ('acta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.muestraagua')),
            ],
        ),
        migrations.AddField(
            model_name='muestraagua',
            name='planta_industrial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.plantaindustrial'),
        ),
        migrations.AddField(
            model_name='muestraagua',
            name='tipo_analisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.tipoanalisisagua'),
        ),
    ]
