# Generated by Django 4.2 on 2025-04-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_remove_auditoria_conclusion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntapredefinida',
            name='es_evaluacion',
        ),
    ]
