# Generated by Django 4.2 on 2025-06-26 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_muestraagua_plantaindustrial_tipoanalisisagua_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadProductiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('razon_social', models.CharField(max_length=100)),
                ('renspa', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ubicacion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuestraLeche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('volumen_litros', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unidad_productiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.unidadproductiva')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigacionAnalitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.CharField(max_length=50)),
                ('protocolo', models.FileField(blank=True, null=True, upload_to='protocolos/')),
                ('detectado', models.BooleanField()),
                ('fecha_resultado', models.DateField()),
                ('analito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.analito')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigaciones', to='questions.muestraleche')),
            ],
        ),
    ]
