# Generated by Django 4.2 on 2025-04-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auditoria_auditores_acompanantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='lineas_auditadas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lineas de producción auditadas'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='auditores_acompanantes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Auditores acompañantes'),
        ),
    ]
