# Generated by Django 4.2 on 2025-04-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auditoria_lineas_auditadas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntapredefinida',
            options={'ordering': ['numero_pregunta']},
        ),
        migrations.AddField(
            model_name='preguntapredefinida',
            name='numero_pregunta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
