# Generated by Django 4.2 on 2025-04-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_remove_preguntapredefinida_es_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='usa_puntaje',
            field=models.BooleanField(default=True),
        ),
    ]
