# Generated by Django 4.2 on 2025-04-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_checklist_usa_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='resultado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='auditorias/'),
        ),
    ]
