# Generated by Django 4.2 on 2025-06-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_unidadproductiva_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacionanalitica',
            name='detectado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investigacionanalitica',
            name='fecha_resultado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
