# Generated by Django 4.2 on 2025-06-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_alter_investigacionanalitica_detectado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestraleche',
            name='codigo_muestra',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de muestreo'),
        ),
    ]
