# Generated by Django 4.2 on 2025-04-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auditoria_resultado_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ['-fecha']},
        ),
    ]
