# Generated by Django 4.2 on 2025-06-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_muestraleche_codigo_muestra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigacionanalitica',
            name='detectado',
        ),
        migrations.AddField(
            model_name='investigacionanalitica',
            name='estado_resultado',
            field=models.CharField(choices=[('aceptable', 'Aceptable'), ('no_aceptable', 'No aceptable'), ('falta', 'Falta resultado')], default='falta', max_length=20),
        ),
    ]
