# Generated by Django 4.2 on 2025-04-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_alter_auditoria_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntapredefinida',
            name='numero_pregunta',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
