# Generated by Django 4.2 on 2025-04-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_ppr_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppr',
            name='requisito',
            field=models.TextField(blank=True, null=True),
        ),
    ]
