# Generated by Django 4.2 on 2025-04-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_alter_ppr_requisito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='texto',
            field=models.CharField(max_length=255),
        ),
    ]
